version: 2
updates:
  # Keep Downstyler submodule up to date
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "submodule"
      include: "scope"
