version: 2
updates:
  # Keep Downstyler submodule up to date
  - package-ecosystem: "gitsubmodule"
    directory: "/vendor"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "submodule" # Example: "submodule: bump vendor/downstyler from `abc1234` to `def5678`"
      include: "scope"
